title: The Muslim Post | TMP News
description: "The Muslim Post (TMP News) is a community of thinkers, learners, and experts. Discover insightful posts and contribute your own perspective on World Politics, Indian Politics, and the Muslim World."
permalink: /news/:categories/:title/

# Site-wide SEO keywords
keywords: ["The Muslim Post", "TMP News", "Muslim post", "World Politics", "Indian Politics", "Muslim World", "Technology", "Global Economy"]

# Add this section to explicitly enable the sitemap plugin
plugins:
  - jekyll-sitemap

baseurl: "" 
url: "https://www.tmpnews.com"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Tell Jekyll to process the _live_updates folder as a collection
collections:
  live_updates:
    output: true # This ensures each document becomes its own page

# Tell Jekyll to include these files/folders in the final build
include:
  - cms.html
  - liveCMS.html
  - latest.html
  - .well-known

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md